# Generated by Django 5.0.7 on 2024-08-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_bankform_billing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bankform',
        ),
        migrations.DeleteModel(
            name='billing',
        ),
    ]
